insert into generate
    (ImageID, PromptID, Type)
values
    (1, 1, "Positive"),
    (1, 2, "Negative"),
    (2, 3, "Positive"),
    (2, 2, "Negative"),
    (3, 4, "Positive"),
    (3, 5, "negative"),
    (4, 6, "Positive"),
    (4, 7, "Negative"),
    (5, 8, "Positive"),
    (5, 2, "Negative"),
    (6, 9, "Positive"),
    (6, 2, "Negative"),
    (7, 10, "Positive"),
    (7, 2, "Negative"),
    (8, 11, "Positive"),
    (8, 2, "Negative"),
    (9, 12, "Positive"),
    (9, 2, "Negative");
